import React, {useEffect} from "react";
import {Paper, Table, TableBody, TableCell, TableContainer, TableHead, TableRow} from "@material-ui/core";
import {TCoin, TCoinDiff} from "../../types";
import {inject, observer} from "mobx-react";
import CurrenciesStore from "../../stores/currenciesStore";

interface ICtyptoTable {
    classes: any;
    currenciesStore?: CurrenciesStore;
}


const CryptoTable = inject('currenciesStore')(
    observer(({classes, currenciesStore}: ICtyptoTable) => {
            const items: TCoin[] = currenciesStore!.getItems;
            const diffObj: TCoinDiff = currenciesStore!.getDiffobject;


            useEffect(() => {
                if (currenciesStore) {
                    currenciesStore?.fetchCoins()
                }
                setTimeout(() => {
                    currenciesStore?.setItems([
                        {
                            "CoinInfo": {
                                "Id": "1182",
                                "Name": "BTC",
                                "FullName": "Bitcoin",
                                "Internal": "BTC",
                                "ImageUrl": "/media/37746251/btc.png",
                                "Url": "/coins/btc/overview",
                                "Algorithm": "SHA-256",
                                "ProofType": "PoW",
                                "Rating": {
                                    "Weiss": {
                                        "Rating": "B+",
                                        "TechnologyAdoptionRating": "A-",
                                        "MarketPerformanceRating": "B-"
                                    }
                                },
                                "NetHashesPerSecond": 136473557835965630000,
                                "BlockNumber": 674455,
                                "BlockTime": 660.9685,
                                "BlockReward": 6.25,
                                "AssetLaunchDate": "2009-01-03",
                                "MaxSupply": 20999999.9769,
                                "Type": 1,
                                "DocumentType": "Webpagecoinp"
                            },
                            "RAW": {
                                "USD": {
                                    "TYPE": "5",
                                    "MARKET": "CCCAGG",
                                    "FROMSYMBOL": "BTC",
                                    "TOSYMBOL": "USD",
                                    "FLAGS": "2052",
                                    "PRICE": 60301.84,
                                    "LASTUPDATE": 1615662648,
                                    "MEDIAN": 60277.9,
                                    "LASTVOLUME": 0.00079199,
                                    "LASTVOLUMETO": 47.7662078437,
                                    "LASTTRADEID": "144508331",
                                    "VOLUMEDAY": 45391.65054419662,
                                    "VOLUMEDAYTO": 2677778537.894156,
                                    "VOLUME24HOUR": 51675.72417450001,
                                    "VOLUME24HOURTO": 3035565916.8921795,
                                    "OPENDAY": 57255.84,
                                    "HIGHDAY": 60426.41,
                                    "LOWDAY": 56103.32,
                                    "OPEN24HOUR": 56968.4,
                                    "HIGH24HOUR": 60455.69,
                                    "LOW24HOUR": 56093.23,
                                    "LASTMARKET": "Coinbase",
                                    "VOLUMEHOUR": 179.34457067000014,
                                    "VOLUMEHOURTO": 10811681.192210441,
                                    "OPENHOUR": 60294.78,
                                    "HIGHHOUR": 60317.66,
                                    "LOWHOUR": 60216.89,
                                    "TOPTIERVOLUME24HOUR": 51675.72417450001,
                                    "TOPTIERVOLUME24HOURTO": 3035565916.8921795,
                                    "CHANGE24HOUR": 3333.439999999995,
                                    "CHANGEPCT24HOUR": 5.8513842761952155,
                                    "CHANGEDAY": 3046,
                                    "CHANGEPCTDAY": 5.319981332908574,
                                    "CHANGEHOUR": 7.059999999997672,
                                    "CHANGEPCTHOUR": 0.011709139663496031,
                                    "CONVERSIONTYPE": "direct",
                                    "CONVERSIONSYMBOL": "",
                                    "SUPPLY": 18652850,
                                    "MKTCAP": 1124801176244,
                                    "MKTCAPPENALTY": 0,
                                    "TOTALVOLUME24H": 269783.6323349772,
                                    "TOTALVOLUME24HTO": 16187874097.51997,
                                    "TOTALTOPTIERVOLUME24H": 269506.49851359444,
                                    "TOTALTOPTIERVOLUME24HTO": 16171162418.164358,
                                    "IMAGEURL": "/media/37746251/btc.png"
                                }
                            },
                            "DISPLAY": {
                                "USD": {
                                    "FROMSYMBOL": "Ƀ",
                                    "TOSYMBOL": "$",
                                    "MARKET": "CryptoCompare Index",
                                    "PRICE": "$ 60,301.8",
                                    "LASTUPDATE": "Just now",
                                    "LASTVOLUME": "Ƀ 0.0007920",
                                    "LASTVOLUMETO": "$ 47.77",
                                    "LASTTRADEID": "144508331",
                                    "VOLUMEDAY": "Ƀ 45,391.7",
                                    "VOLUMEDAYTO": "$ 2,677,778,537.9",
                                    "VOLUME24HOUR": "Ƀ 51,675.7",
                                    "VOLUME24HOURTO": "$ 3,035,565,916.9",
                                    "OPENDAY": "$ 57,255.8",
                                    "HIGHDAY": "$ 60,426.4",
                                    "LOWDAY": "$ 56,103.3",
                                    "OPEN24HOUR": "$ 56,968.4",
                                    "HIGH24HOUR": "$ 60,455.7",
                                    "LOW24HOUR": "$ 56,093.2",
                                    "LASTMARKET": "Coinbase",
                                    "VOLUMEHOUR": "Ƀ 179.34",
                                    "VOLUMEHOURTO": "$ 10,811,681.2",
                                    "OPENHOUR": "$ 60,294.8",
                                    "HIGHHOUR": "$ 60,317.7",
                                    "LOWHOUR": "$ 60,216.9",
                                    "TOPTIERVOLUME24HOUR": "Ƀ 51,675.7",
                                    "TOPTIERVOLUME24HOURTO": "$ 3,035,565,916.9",
                                    "CHANGE24HOUR": "$ 3,333.44",
                                    "CHANGEPCT24HOUR": "5.85",
                                    "CHANGEDAY": "$ 3,046.00",
                                    "CHANGEPCTDAY": "5.32",
                                    "CHANGEHOUR": "$ 7.06",
                                    "CHANGEPCTHOUR": "0.01",
                                    "CONVERSIONTYPE": "direct",
                                    "CONVERSIONSYMBOL": "",
                                    "SUPPLY": "Ƀ 18,652,850.0",
                                    "MKTCAP": "$ 1,124.80 B",
                                    "MKTCAPPENALTY": "0 %",
                                    "TOTALVOLUME24H": "Ƀ 269.78 K",
                                    "TOTALVOLUME24HTO": "$ 16.19 B",
                                    "TOTALTOPTIERVOLUME24H": "Ƀ 269.51 K",
                                    "TOTALTOPTIERVOLUME24HTO": "$ 16.17 B",
                                    "IMAGEURL": "/media/37746251/btc.png"
                                }
                            }
                        },
                        {
                            "CoinInfo": {
                                "Id": "7605",
                                "Name": "ETH",
                                "FullName": "Ethereum",
                                "Internal": "ETH",
                                "ImageUrl": "/media/37746238/eth.png",
                                "Url": "/coins/eth/overview",
                                "Algorithm": "Ethash",
                                "ProofType": "PoW",
                                "Rating": {
                                    "Weiss": {
                                        "Rating": "B+",
                                        "TechnologyAdoptionRating": "A-",
                                        "MarketPerformanceRating": "C+"
                                    }
                                },
                                "NetHashesPerSecond": 437353101648258.75,
                                "BlockNumber": 12032004,
                                "BlockTime": 13.176443975267683,
                                "BlockReward": 3.9073255188655196,
                                "AssetLaunchDate": "2015-07-30",
                                "MaxSupply": -1,
                                "Type": 1,
                                "DocumentType": "Webpagecoinp"
                            },
                            "RAW": {
                                "USD": {
                                    "TYPE": "5",
                                    "MARKET": "CCCAGG",
                                    "FROMSYMBOL": "ETH",
                                    "TOSYMBOL": "USD",
                                    "FLAGS": "2050",
                                    "PRICE": 1910.18,
                                    "LASTUPDATE": 1615662648,
                                    "MEDIAN": 1910,
                                    "LASTVOLUME": 1.04,
                                    "LASTVOLUMETO": 1986.4728,
                                    "LASTTRADEID": "92231817",
                                    "VOLUMEDAY": 471641.1744379698,
                                    "VOLUMEDAYTO": 871808162.7843431,
                                    "VOLUME24HOUR": 560320.19860747,
                                    "VOLUME24HOURTO": 1026762181.142854,
                                    "OPENDAY": 1767.75,
                                    "HIGHDAY": 1920.7,
                                    "LOWDAY": 1728.87,
                                    "OPEN24HOUR": 1740.11,
                                    "HIGH24HOUR": 1920.91,
                                    "LOW24HOUR": 1724.53,
                                    "LASTMARKET": "Coinbase",
                                    "VOLUMEHOUR": 4391.570296400008,
                                    "VOLUMEHOURTO": 8391417.034255233,
                                    "OPENHOUR": 1912.72,
                                    "HIGHHOUR": 1912.98,
                                    "LOWHOUR": 1906.42,
                                    "TOPTIERVOLUME24HOUR": 560320.19860747,
                                    "TOPTIERVOLUME24HOURTO": 1026762181.142854,
                                    "CHANGE24HOUR": 170.07000000000016,
                                    "CHANGEPCT24HOUR": 9.773520064823499,
                                    "CHANGEDAY": 142.43000000000006,
                                    "CHANGEPCTDAY": 8.057134775845004,
                                    "CHANGEHOUR": -2.5399999999999636,
                                    "CHANGEPCTHOUR": -0.1327951817307271,
                                    "CONVERSIONTYPE": "direct",
                                    "CONVERSIONSYMBOL": "",
                                    "SUPPLY": 115036306.499,
                                    "MKTCAP": 219740051948.25986,
                                    "MKTCAPPENALTY": 0,
                                    "TOTALVOLUME24H": 3771172.0493351133,
                                    "TOTALVOLUME24HTO": 7160067169.365784,
                                    "TOTALTOPTIERVOLUME24H": 3750267.961238882,
                                    "TOTALTOPTIERVOLUME24HTO": 7120136598.366125,
                                    "IMAGEURL": "/media/37746238/eth.png"
                                }
                            },
                            "DISPLAY": {
                                "USD": {
                                    "FROMSYMBOL": "Ξ",
                                    "TOSYMBOL": "$",
                                    "MARKET": "CryptoCompare Index",
                                    "PRICE": "$ 1,910.18",
                                    "LASTUPDATE": "Just now",
                                    "LASTVOLUME": "Ξ 1.04",
                                    "LASTVOLUMETO": "$ 1,986.47",
                                    "LASTTRADEID": "92231817",
                                    "VOLUMEDAY": "Ξ 471,641.2",
                                    "VOLUMEDAYTO": "$ 871,808,162.8",
                                    "VOLUME24HOUR": "Ξ 560,320.2",
                                    "VOLUME24HOURTO": "$ 1,026,762,181.1",
                                    "OPENDAY": "$ 1,767.75",
                                    "HIGHDAY": "$ 1,920.70",
                                    "LOWDAY": "$ 1,728.87",
                                    "OPEN24HOUR": "$ 1,740.11",
                                    "HIGH24HOUR": "$ 1,920.91",
                                    "LOW24HOUR": "$ 1,724.53",
                                    "LASTMARKET": "Coinbase",
                                    "VOLUMEHOUR": "Ξ 4,391.57",
                                    "VOLUMEHOURTO": "$ 8,391,417.0",
                                    "OPENHOUR": "$ 1,912.72",
                                    "HIGHHOUR": "$ 1,912.98",
                                    "LOWHOUR": "$ 1,906.42",
                                    "TOPTIERVOLUME24HOUR": "Ξ 560,320.2",
                                    "TOPTIERVOLUME24HOURTO": "$ 1,026,762,181.1",
                                    "CHANGE24HOUR": "$ 170.07",
                                    "CHANGEPCT24HOUR": "9.77",
                                    "CHANGEDAY": "$ 142.43",
                                    "CHANGEPCTDAY": "8.06",
                                    "CHANGEHOUR": "$ -2.54",
                                    "CHANGEPCTHOUR": "-0.13",
                                    "CONVERSIONTYPE": "direct",
                                    "CONVERSIONSYMBOL": "",
                                    "SUPPLY": "Ξ 115,036,306.5",
                                    "MKTCAP": "$ 219.74 B",
                                    "MKTCAPPENALTY": "0 %",
                                    "TOTALVOLUME24H": "Ξ 3.77 M",
                                    "TOTALVOLUME24HTO": "$ 7.16 B",
                                    "TOTALTOPTIERVOLUME24H": "Ξ 3.75 M",
                                    "TOTALTOPTIERVOLUME24HTO": "$ 7.12 B",
                                    "IMAGEURL": "/media/37746238/eth.png"
                                }
                            }
                        },
                        {
                            "CoinInfo": {
                                "Id": "931799",
                                "Name": "CHZ",
                                "FullName": "Chiliz",
                                "Internal": "CHZ",
                                "ImageUrl": "/media/35651381/chz.png",
                                "Url": "/coins/chz/overview",
                                "Algorithm": "N/A",
                                "ProofType": "N/A",
                                "Rating": {
                                    "Weiss": {
                                        "Rating": "",
                                        "TechnologyAdoptionRating": "",
                                        "MarketPerformanceRating": ""
                                    }
                                },
                                "NetHashesPerSecond": 0,
                                "BlockNumber": 0,
                                "BlockTime": 0,
                                "BlockReward": 0,
                                "AssetLaunchDate": "2018-10-26",
                                "MaxSupply": -1,
                                "Type": 1,
                                "DocumentType": "Webpagecoinp"
                            },
                            "RAW": {
                                "USD": {
                                    "TYPE": "5",
                                    "MARKET": "CCCAGG",
                                    "FROMSYMBOL": "CHZ",
                                    "TOSYMBOL": "USD",
                                    "FLAGS": "513",
                                    "PRICE": 0.7255,
                                    "LASTUPDATE": 1615662549,
                                    "MEDIAN": 0.72548,
                                    "LASTVOLUME": 128,
                                    "LASTVOLUMETO": 92.86144,
                                    "LASTTRADEID": "641938171",
                                    "VOLUMEDAY": 2874223.905215061,
                                    "VOLUMEDAYTO": 2236892.7726826966,
                                    "VOLUME24HOUR": 4454410.72847376,
                                    "VOLUME24HOURTO": 3360566.88509457,
                                    "OPENDAY": 0.7246,
                                    "HIGHDAY": 0.9,
                                    "LOWDAY": 0.6658,
                                    "OPEN24HOUR": 0.67,
                                    "HIGH24HOUR": 0.92,
                                    "LOW24HOUR": 0.4208,
                                    "LASTMARKET": "Bitfinex",
                                    "VOLUMEHOUR": 1594.0479960100001,
                                    "VOLUMEHOURTO": 1134.0237261636,
                                    "OPENHOUR": 0.72,
                                    "HIGHHOUR": 0.7255,
                                    "LOWHOUR": 0.71,
                                    "TOPTIERVOLUME24HOUR": 4454410.72847376,
                                    "TOPTIERVOLUME24HOURTO": 3360566.88509457,
                                    "CHANGE24HOUR": 0.055499999999999994,
                                    "CHANGEPCT24HOUR": 8.283582089552237,
                                    "CHANGEDAY": 0.0009000000000000119,
                                    "CHANGEPCTDAY": 0.12420645873585591,
                                    "CHANGEHOUR": 0.00550000000000006,
                                    "CHANGEPCTHOUR": 0.7638888888888973,
                                    "CONVERSIONTYPE": "direct",
                                    "CONVERSIONSYMBOL": "",
                                    "SUPPLY": 8888888888,
                                    "MKTCAP": 6448888888.244,
                                    "MKTCAPPENALTY": 0,
                                    "TOTALVOLUME24H": 4912133986.187049,
                                    "TOTALVOLUME24HTO": 3563882098.880291,
                                    "TOTALTOPTIERVOLUME24H": 4912133986.187049,
                                    "TOTALTOPTIERVOLUME24HTO": 3563882098.880291,
                                    "IMAGEURL": "/media/35651381/chz.png"
                                }
                            },
                            "DISPLAY": {
                                "USD": {
                                    "FROMSYMBOL": "CHZ",
                                    "TOSYMBOL": "$",
                                    "MARKET": "CryptoCompare Index",
                                    "PRICE": "$ 0.7255",
                                    "LASTUPDATE": "1 min ago",
                                    "LASTVOLUME": "CHZ 128.00",
                                    "LASTVOLUMETO": "$ 92.86",
                                    "LASTTRADEID": "641938171",
                                    "VOLUMEDAY": "CHZ 2,874,223.9",
                                    "VOLUMEDAYTO": "$ 2,236,892.8",
                                    "VOLUME24HOUR": "CHZ 4,454,410.7",
                                    "VOLUME24HOURTO": "$ 3,360,566.9",
                                    "OPENDAY": "$ 0.7246",
                                    "HIGHDAY": "$ 0.9000",
                                    "LOWDAY": "$ 0.6658",
                                    "OPEN24HOUR": "$ 0.6700",
                                    "HIGH24HOUR": "$ 0.9200",
                                    "LOW24HOUR": "$ 0.4208",
                                    "LASTMARKET": "Bitfinex",
                                    "VOLUMEHOUR": "CHZ 1,594.05",
                                    "VOLUMEHOURTO": "$ 1,134.02",
                                    "OPENHOUR": "$ 0.7200",
                                    "HIGHHOUR": "$ 0.7255",
                                    "LOWHOUR": "$ 0.7100",
                                    "TOPTIERVOLUME24HOUR": "CHZ 4,454,410.7",
                                    "TOPTIERVOLUME24HOURTO": "$ 3,360,566.9",
                                    "CHANGE24HOUR": "$ 0.055",
                                    "CHANGEPCT24HOUR": "8.28",
                                    "CHANGEDAY": "$ 0.00090",
                                    "CHANGEPCTDAY": "0.12",
                                    "CHANGEHOUR": "$ 0.0055",
                                    "CHANGEPCTHOUR": "0.76",
                                    "CONVERSIONTYPE": "direct",
                                    "CONVERSIONSYMBOL": "",
                                    "SUPPLY": "CHZ 8,888,888,888.0",
                                    "MKTCAP": "$ 6.45 B",
                                    "MKTCAPPENALTY": "0 %",
                                    "TOTALVOLUME24H": "CHZ 4.91 B",
                                    "TOTALVOLUME24HTO": "$ 3.56 B",
                                    "TOTALTOPTIERVOLUME24H": "CHZ 4.91 B",
                                    "TOTALTOPTIERVOLUME24HTO": "$ 3.56 B",
                                    "IMAGEURL": "/media/35651381/chz.png"
                                }
                            }
                        },
                        {
                            "CoinInfo": {
                                "Id": "199148",
                                "Name": "MANA",
                                "FullName": "Decentraland",
                                "Internal": "MANA",
                                "ImageUrl": "/media/37746241/mana.png",
                                "Url": "/coins/mana/overview",
                                "Algorithm": "N/A",
                                "ProofType": "N/A",
                                "Rating": {
                                    "Weiss": {
                                        "Rating": "",
                                        "TechnologyAdoptionRating": "",
                                        "MarketPerformanceRating": ""
                                    }
                                },
                                "NetHashesPerSecond": 0,
                                "BlockNumber": 0,
                                "BlockTime": 0,
                                "BlockReward": 0,
                                "AssetLaunchDate": "2017-08-08",
                                "MaxSupply": -1,
                                "Type": 1,
                                "DocumentType": "Webpagecoinp"
                            },
                            "RAW": {
                                "USD": {
                                    "TYPE": "5",
                                    "MARKET": "CCCAGG",
                                    "FROMSYMBOL": "MANA",
                                    "TOSYMBOL": "USD",
                                    "FLAGS": "2052",
                                    "PRICE": 1.116,
                                    "LASTUPDATE": 1615662645,
                                    "MEDIAN": 1.108,
                                    "LASTVOLUME": 9.31,
                                    "LASTVOLUMETO": 10.454199,
                                    "LASTTRADEID": "314851",
                                    "VOLUMEDAY": 68989002.79518871,
                                    "VOLUMEDAYTO": 60364588.16328013,
                                    "VOLUME24HOUR": 81922966.3894642,
                                    "VOLUME24HOURTO": 68485980.96320665,
                                    "OPENDAY": 0.6595,
                                    "HIGHDAY": 1.435,
                                    "LOWDAY": 0.6148,
                                    "OPEN24HOUR": 0.5481,
                                    "HIGH24HOUR": 1.644,
                                    "LOW24HOUR": 0.5382,
                                    "LASTMARKET": "binanceusa",
                                    "VOLUMEHOUR": 2344564.3830122272,
                                    "VOLUMEHOURTO": 2581533.1023340616,
                                    "OPENHOUR": 1.029,
                                    "HIGHHOUR": 1.131,
                                    "LOWHOUR": 1.026,
                                    "TOPTIERVOLUME24HOUR": 81922966.3894642,
                                    "TOPTIERVOLUME24HOURTO": 68485980.96320665,
                                    "CHANGE24HOUR": 0.5679000000000001,
                                    "CHANGEPCT24HOUR": 103.61247947454845,
                                    "CHANGEDAY": 0.45650000000000013,
                                    "CHANGEPCTDAY": 69.21910538286583,
                                    "CHANGEHOUR": 0.08700000000000019,
                                    "CHANGEPCTHOUR": 8.454810495626841,
                                    "CONVERSIONTYPE": "direct",
                                    "CONVERSIONSYMBOL": "",
                                    "SUPPLY": 2194689027.320146,
                                    "MKTCAP": 2449272954.489283,
                                    "MKTCAPPENALTY": 0,
                                    "TOTALVOLUME24H": 1971236816.6557183,
                                    "TOTALVOLUME24HTO": 2176960237.8603463,
                                    "TOTALTOPTIERVOLUME24H": 1963872265.6557207,
                                    "TOTALTOPTIERVOLUME24HTO": 2168741398.9443493,
                                    "IMAGEURL": "/media/37746241/mana.png"
                                }
                            },
                            "DISPLAY": {
                                "USD": {
                                    "FROMSYMBOL": "MANA",
                                    "TOSYMBOL": "$",
                                    "MARKET": "CryptoCompare Index",
                                    "PRICE": "$ 1.12",
                                    "LASTUPDATE": "Just now",
                                    "LASTVOLUME": "MANA 9.31",
                                    "LASTVOLUMETO": "$ 10.45",
                                    "LASTTRADEID": "314851",
                                    "VOLUMEDAY": "MANA 68,989,002.8",
                                    "VOLUMEDAYTO": "$ 60,364,588.2",
                                    "VOLUME24HOUR": "MANA 81,922,966.4",
                                    "VOLUME24HOURTO": "$ 68,485,981.0",
                                    "OPENDAY": "$ 0.6595",
                                    "HIGHDAY": "$ 1.44",
                                    "LOWDAY": "$ 0.6148",
                                    "OPEN24HOUR": "$ 0.5481",
                                    "HIGH24HOUR": "$ 1.64",
                                    "LOW24HOUR": "$ 0.5382",
                                    "LASTMARKET": "binanceusa",
                                    "VOLUMEHOUR": "MANA 2,344,564.4",
                                    "VOLUMEHOURTO": "$ 2,581,533.1",
                                    "OPENHOUR": "$ 1.03",
                                    "HIGHHOUR": "$ 1.13",
                                    "LOWHOUR": "$ 1.03",
                                    "TOPTIERVOLUME24HOUR": "MANA 81,922,966.4",
                                    "TOPTIERVOLUME24HOURTO": "$ 68,485,981.0",
                                    "CHANGE24HOUR": "$ 0.57",
                                    "CHANGEPCT24HOUR": "103.61",
                                    "CHANGEDAY": "$ 0.46",
                                    "CHANGEPCTDAY": "69.22",
                                    "CHANGEHOUR": "$ 0.087",
                                    "CHANGEPCTHOUR": "8.45",
                                    "CONVERSIONTYPE": "direct",
                                    "CONVERSIONSYMBOL": "",
                                    "SUPPLY": "MANA 2,194,689,027.3",
                                    "MKTCAP": "$ 2.45 B",
                                    "MKTCAPPENALTY": "0 %",
                                    "TOTALVOLUME24H": "MANA 1.97 B",
                                    "TOTALVOLUME24HTO": "$ 2.18 B",
                                    "TOTALTOPTIERVOLUME24H": "MANA 1.96 B",
                                    "TOTALTOPTIERVOLUME24HTO": "$ 2.17 B",
                                    "IMAGEURL": "/media/37746241/mana.png"
                                }
                            }
                        },
                        {
                            "CoinInfo": {
                                "Id": "321992",
                                "Name": "ADA",
                                "FullName": "Cardano",
                                "Internal": "ADA",
                                "ImageUrl": "/media/37746235/ada.png",
                                "Url": "/coins/ada/overview",
                                "Algorithm": "Ouroboros",
                                "ProofType": "PoS",
                                "Rating": {
                                    "Weiss": {
                                        "Rating": "B-",
                                        "TechnologyAdoptionRating": "B-",
                                        "MarketPerformanceRating": "B"
                                    }
                                },
                                "NetHashesPerSecond": 0,
                                "BlockNumber": 5457043,
                                "BlockTime": 0,
                                "BlockReward": 0,
                                "AssetLaunchDate": "2017-10-05",
                                "MaxSupply": 45000000000,
                                "Type": 1,
                                "DocumentType": "Webpagecoinp"
                            },
                            "RAW": {
                                "USD": {
                                    "TYPE": "5",
                                    "MARKET": "CCCAGG",
                                    "FROMSYMBOL": "ADA",
                                    "TOSYMBOL": "USD",
                                    "FLAGS": "1028",
                                    "PRICE": 1.109,
                                    "LASTUPDATE": 1615662654,
                                    "MEDIAN": 1.10925723,
                                    "LASTVOLUME": 2000,
                                    "LASTVOLUMETO": 2218,
                                    "LASTTRADEID": "641932091",
                                    "VOLUMEDAY": 109221944.87916714,
                                    "VOLUMEDAYTO": 118493588.35201994,
                                    "VOLUME24HOUR": 127949421.08925287,
                                    "VOLUME24HOURTO": 137945527.95740312,
                                    "OPENDAY": 1.032,
                                    "HIGHDAY": 1.19,
                                    "LOWDAY": 0.9845,
                                    "OPEN24HOUR": 1.043,
                                    "HIGH24HOUR": 1.19,
                                    "LOW24HOUR": 0.983,
                                    "LASTMARKET": "Bitfinex",
                                    "VOLUMEHOUR": 441749.85200332,
                                    "VOLUMEHOURTO": 490858.8959776952,
                                    "OPENHOUR": 1.115,
                                    "HIGHHOUR": 1.116,
                                    "LOWHOUR": 1.109,
                                    "TOPTIERVOLUME24HOUR": 127949421.08925287,
                                    "TOPTIERVOLUME24HOURTO": 137945527.95740312,
                                    "CHANGE24HOUR": 0.06600000000000006,
                                    "CHANGEPCT24HOUR": 6.327900287631838,
                                    "CHANGEDAY": 0.07699999999999996,
                                    "CHANGEPCTDAY": 7.461240310077515,
                                    "CHANGEHOUR": -0.006000000000000005,
                                    "CHANGEPCTHOUR": -0.5381165919282516,
                                    "CONVERSIONTYPE": "direct",
                                    "CONVERSIONSYMBOL": "",
                                    "SUPPLY": 31984031706.957413,
                                    "MKTCAP": 35470291163.01577,
                                    "MKTCAPPENALTY": 0,
                                    "TOTALVOLUME24H": 1701872379.5583527,
                                    "TOTALVOLUME24HTO": 1883426088.8996348,
                                    "TOTALTOPTIERVOLUME24H": 1697102405.886471,
                                    "TOTALTOPTIERVOLUME24HTO": 1878136188.097518,
                                    "IMAGEURL": "/media/37746235/ada.png"
                                }
                            },
                            "DISPLAY": {
                                "USD": {
                                    "FROMSYMBOL": "ADA",
                                    "TOSYMBOL": "$",
                                    "MARKET": "CryptoCompare Index",
                                    "PRICE": "$ 1.11",
                                    "LASTUPDATE": "Just now",
                                    "LASTVOLUME": "ADA 2,000.00",
                                    "LASTVOLUMETO": "$ 2,218.00",
                                    "LASTTRADEID": "641932091",
                                    "VOLUMEDAY": "ADA 109,221,944.9",
                                    "VOLUMEDAYTO": "$ 118,493,588.4",
                                    "VOLUME24HOUR": "ADA 127,949,421.1",
                                    "VOLUME24HOURTO": "$ 137,945,528.0",
                                    "OPENDAY": "$ 1.03",
                                    "HIGHDAY": "$ 1.19",
                                    "LOWDAY": "$ 0.9845",
                                    "OPEN24HOUR": "$ 1.04",
                                    "HIGH24HOUR": "$ 1.19",
                                    "LOW24HOUR": "$ 0.9830",
                                    "LASTMARKET": "Bitfinex",
                                    "VOLUMEHOUR": "ADA 441,749.9",
                                    "VOLUMEHOURTO": "$ 490,858.9",
                                    "OPENHOUR": "$ 1.12",
                                    "HIGHHOUR": "$ 1.12",
                                    "LOWHOUR": "$ 1.11",
                                    "TOPTIERVOLUME24HOUR": "ADA 127,949,421.1",
                                    "TOPTIERVOLUME24HOURTO": "$ 137,945,528.0",
                                    "CHANGE24HOUR": "$ 0.066",
                                    "CHANGEPCT24HOUR": "6.33",
                                    "CHANGEDAY": "$ 0.077",
                                    "CHANGEPCTDAY": "7.46",
                                    "CHANGEHOUR": "$ -0.0060",
                                    "CHANGEPCTHOUR": "-0.54",
                                    "CONVERSIONTYPE": "direct",
                                    "CONVERSIONSYMBOL": "",
                                    "SUPPLY": "ADA 31,984,031,707.0",
                                    "MKTCAP": "$ 35.47 B",
                                    "MKTCAPPENALTY": "0 %",
                                    "TOTALVOLUME24H": "ADA 1.70 B",
                                    "TOTALVOLUME24HTO": "$ 1.88 B",
                                    "TOTALTOPTIERVOLUME24H": "ADA 1.70 B",
                                    "TOTALTOPTIERVOLUME24HTO": "$ 1.88 B",
                                    "IMAGEURL": "/media/37746235/ada.png"
                                }
                            }
                        },
                        {
                            "CoinInfo": {
                                "Id": "3808",
                                "Name": "LTC",
                                "FullName": "Litecoin",
                                "Internal": "LTC",
                                "ImageUrl": "/media/37746243/ltc.png",
                                "Url": "/coins/ltc/overview",
                                "Algorithm": "Scrypt",
                                "ProofType": "PoW",
                                "Rating": {
                                    "Weiss": {
                                        "Rating": "B-",
                                        "TechnologyAdoptionRating": "B-",
                                        "MarketPerformanceRating": "C-"
                                    }
                                },
                                "NetHashesPerSecond": 269710949729319,
                                "BlockNumber": 2016265,
                                "BlockTime": 155,
                                "BlockReward": 12.51176654,
                                "AssetLaunchDate": "2011-10-13",
                                "MaxSupply": 84000000,
                                "Type": 1,
                                "DocumentType": "Webpagecoinp"
                            },
                            "RAW": {
                                "USD": {
                                    "TYPE": "5",
                                    "MARKET": "CCCAGG",
                                    "FROMSYMBOL": "LTC",
                                    "TOSYMBOL": "USD",
                                    "FLAGS": "1028",
                                    "PRICE": 226.17,
                                    "LASTUPDATE": 1615662645,
                                    "MEDIAN": 226.26,
                                    "LASTVOLUME": 1.09993367,
                                    "LASTVOLUMETO": 248.7499994705,
                                    "LASTTRADEID": "5WQDTDZEYNCI",
                                    "VOLUMEDAY": 712819.6277047291,
                                    "VOLUMEDAYTO": 158670994.51183507,
                                    "VOLUME24HOUR": 1088985.3014908899,
                                    "VOLUME24HOURTO": 240993646.6186823,
                                    "OPENDAY": 220.76,
                                    "HIGHDAY": 229.22,
                                    "LOWDAY": 212.76,
                                    "OPEN24HOUR": 210.46,
                                    "HIGH24HOUR": 229.29,
                                    "LOW24HOUR": 209.58,
                                    "LASTMARKET": "itBit",
                                    "VOLUMEHOUR": 5129.346624629996,
                                    "VOLUMEHOURTO": 1162664.650038613,
                                    "OPENHOUR": 227.63,
                                    "HIGHHOUR": 227.71,
                                    "LOWHOUR": 226.17,
                                    "TOPTIERVOLUME24HOUR": 1088985.3014908899,
                                    "TOPTIERVOLUME24HOURTO": 240993646.6186823,
                                    "CHANGE24HOUR": 15.70999999999998,
                                    "CHANGEPCT24HOUR": 7.464601349425058,
                                    "CHANGEDAY": 5.409999999999997,
                                    "CHANGEPCTDAY": 2.450625113245152,
                                    "CHANGEHOUR": -1.460000000000008,
                                    "CHANGEPCTHOUR": -0.6413917321969899,
                                    "CONVERSIONTYPE": "direct",
                                    "CONVERSIONSYMBOL": "",
                                    "SUPPLY": 67201358.23347135,
                                    "MKTCAP": 15198931191.664213,
                                    "MKTCAPPENALTY": 0,
                                    "TOTALVOLUME24H": 8231348.753170249,
                                    "TOTALVOLUME24HTO": 1856381988.485003,
                                    "TOTALTOPTIERVOLUME24H": 8210806.225251778,
                                    "TOTALTOPTIERVOLUME24HTO": 1851735884.9456823,
                                    "IMAGEURL": "/media/37746243/ltc.png"
                                }
                            },
                            "DISPLAY": {
                                "USD": {
                                    "FROMSYMBOL": "Ł",
                                    "TOSYMBOL": "$",
                                    "MARKET": "CryptoCompare Index",
                                    "PRICE": "$ 226.17",
                                    "LASTUPDATE": "Just now",
                                    "LASTVOLUME": "Ł 1.10",
                                    "LASTVOLUMETO": "$ 248.75",
                                    "LASTTRADEID": "5WQDTDZEYNCI",
                                    "VOLUMEDAY": "Ł 712,819.6",
                                    "VOLUMEDAYTO": "$ 158,670,994.5",
                                    "VOLUME24HOUR": "Ł 1,088,985.3",
                                    "VOLUME24HOURTO": "$ 240,993,646.6",
                                    "OPENDAY": "$ 220.76",
                                    "HIGHDAY": "$ 229.22",
                                    "LOWDAY": "$ 212.76",
                                    "OPEN24HOUR": "$ 210.46",
                                    "HIGH24HOUR": "$ 229.29",
                                    "LOW24HOUR": "$ 209.58",
                                    "LASTMARKET": "itBit",
                                    "VOLUMEHOUR": "Ł 5,129.35",
                                    "VOLUMEHOURTO": "$ 1,162,664.7",
                                    "OPENHOUR": "$ 227.63",
                                    "HIGHHOUR": "$ 227.71",
                                    "LOWHOUR": "$ 226.17",
                                    "TOPTIERVOLUME24HOUR": "Ł 1,088,985.3",
                                    "TOPTIERVOLUME24HOURTO": "$ 240,993,646.6",
                                    "CHANGE24HOUR": "$ 15.71",
                                    "CHANGEPCT24HOUR": "7.46",
                                    "CHANGEDAY": "$ 5.41",
                                    "CHANGEPCTDAY": "2.45",
                                    "CHANGEHOUR": "$ -1.46",
                                    "CHANGEPCTHOUR": "-0.64",
                                    "CONVERSIONTYPE": "direct",
                                    "CONVERSIONSYMBOL": "",
                                    "SUPPLY": "Ł 67,201,358.2",
                                    "MKTCAP": "$ 15.20 B",
                                    "MKTCAPPENALTY": "0 %",
                                    "TOTALVOLUME24H": "Ł 8.23 M",
                                    "TOTALVOLUME24HTO": "$ 1.86 B",
                                    "TOTALTOPTIERVOLUME24H": "Ł 8.21 M",
                                    "TOTALTOPTIERVOLUME24HTO": "$ 1.85 B",
                                    "IMAGEURL": "/media/37746243/ltc.png"
                                }
                            }
                        },
                        {
                            "CoinInfo": {
                                "Id": "204788",
                                "Name": "BNB",
                                "FullName": "Binance Coin",
                                "Internal": "BNB",
                                "ImageUrl": "/media/37746250/bnb.png",
                                "Url": "/coins/bnb/overview",
                                "Algorithm": "BEP-2",
                                "ProofType": "PoSA",
                                "Rating": {
                                    "Weiss": {
                                        "Rating": "C-",
                                        "TechnologyAdoptionRating": "C-",
                                        "MarketPerformanceRating": "C+"
                                    }
                                },
                                "NetHashesPerSecond": 0,
                                "BlockNumber": 0,
                                "BlockTime": 0,
                                "BlockReward": 0,
                                "AssetLaunchDate": "2017-06-27",
                                "MaxSupply": 170533651.9,
                                "Type": 1,
                                "DocumentType": "Webpagecoinp"
                            },
                            "RAW": {
                                "USD": {
                                    "TYPE": "5",
                                    "MARKET": "CCCAGG",
                                    "FROMSYMBOL": "BNB",
                                    "TOSYMBOL": "USD",
                                    "FLAGS": "2052",
                                    "PRICE": 276.86,
                                    "LASTUPDATE": 1615662644,
                                    "MEDIAN": 276.8513,
                                    "LASTVOLUME": 0.54,
                                    "LASTVOLUMETO": 149.499702,
                                    "LASTTRADEID": "2058291",
                                    "VOLUMEDAY": 75402.78680376001,
                                    "VOLUMEDAYTO": 20535022.777539432,
                                    "VOLUME24HOUR": 90655.89411596,
                                    "VOLUME24HOURTO": 24532266.02489151,
                                    "OPENDAY": 263.56,
                                    "HIGHDAY": 283.77,
                                    "LOWDAY": 255.55,
                                    "OPEN24HOUR": 261.3,
                                    "HIGH24HOUR": 283.77,
                                    "LOW24HOUR": 255.52,
                                    "LASTMARKET": "binanceusa",
                                    "VOLUMEHOUR": 219.34286089000005,
                                    "VOLUMEHOURTO": 60648.12596668791,
                                    "OPENHOUR": 276.46,
                                    "HIGHHOUR": 277.08,
                                    "LOWHOUR": 276.05,
                                    "TOPTIERVOLUME24HOUR": 90655.89411596,
                                    "TOPTIERVOLUME24HOURTO": 24532266.02489151,
                                    "CHANGE24HOUR": 15.560000000000002,
                                    "CHANGEPCT24HOUR": 5.954841178721777,
                                    "CHANGEDAY": 13.300000000000011,
                                    "CHANGEPCTDAY": 5.046289269995452,
                                    "CHANGEHOUR": 0.4000000000000341,
                                    "CHANGEPCTHOUR": 0.14468639224482172,
                                    "CONVERSIONTYPE": "direct",
                                    "CONVERSIONSYMBOL": "",
                                    "SUPPLY": 170533651.9,
                                    "MKTCAP": 47213946865.034004,
                                    "MKTCAPPENALTY": 0,
                                    "TOTALVOLUME24H": 6285019.55190157,
                                    "TOTALVOLUME24HTO": 1739503788.3194156,
                                    "TOTALTOPTIERVOLUME24H": 6285019.55190157,
                                    "TOTALTOPTIERVOLUME24HTO": 1739503788.3194156,
                                    "IMAGEURL": "/media/37746250/bnb.png"
                                }
                            },
                            "DISPLAY": {
                                "USD": {
                                    "FROMSYMBOL": "BNB",
                                    "TOSYMBOL": "$",
                                    "MARKET": "CryptoCompare Index",
                                    "PRICE": "$ 276.86",
                                    "LASTUPDATE": "Just now",
                                    "LASTVOLUME": "BNB 0.5400",
                                    "LASTVOLUMETO": "$ 149.50",
                                    "LASTTRADEID": "2058291",
                                    "VOLUMEDAY": "BNB 75,402.8",
                                    "VOLUMEDAYTO": "$ 20,535,022.8",
                                    "VOLUME24HOUR": "BNB 90,655.9",
                                    "VOLUME24HOURTO": "$ 24,532,266.0",
                                    "OPENDAY": "$ 263.56",
                                    "HIGHDAY": "$ 283.77",
                                    "LOWDAY": "$ 255.55",
                                    "OPEN24HOUR": "$ 261.30",
                                    "HIGH24HOUR": "$ 283.77",
                                    "LOW24HOUR": "$ 255.52",
                                    "LASTMARKET": "binanceusa",
                                    "VOLUMEHOUR": "BNB 219.34",
                                    "VOLUMEHOURTO": "$ 60,648.1",
                                    "OPENHOUR": "$ 276.46",
                                    "HIGHHOUR": "$ 277.08",
                                    "LOWHOUR": "$ 276.05",
                                    "TOPTIERVOLUME24HOUR": "BNB 90,655.9",
                                    "TOPTIERVOLUME24HOURTO": "$ 24,532,266.0",
                                    "CHANGE24HOUR": "$ 15.56",
                                    "CHANGEPCT24HOUR": "5.95",
                                    "CHANGEDAY": "$ 13.30",
                                    "CHANGEPCTDAY": "5.05",
                                    "CHANGEHOUR": "$ 0.40",
                                    "CHANGEPCTHOUR": "0.14",
                                    "CONVERSIONTYPE": "direct",
                                    "CONVERSIONSYMBOL": "",
                                    "SUPPLY": "BNB 170,533,651.9",
                                    "MKTCAP": "$ 47.21 B",
                                    "MKTCAPPENALTY": "0 %",
                                    "TOTALVOLUME24H": "BNB 6.29 M",
                                    "TOTALVOLUME24HTO": "$ 1.74 B",
                                    "TOTALTOPTIERVOLUME24H": "BNB 6.29 M",
                                    "TOTALTOPTIERVOLUME24HTO": "$ 1.74 B",
                                    "IMAGEURL": "/media/37746250/bnb.png"
                                }
                            }
                        },
                        {
                            "CoinInfo": {
                                "Id": "5031",
                                "Name": "XRP",
                                "FullName": "XRP",
                                "Internal": "XRP",
                                "ImageUrl": "/media/37746347/xrp.png",
                                "Url": "/coins/xrp/overview",
                                "Algorithm": "N/A",
                                "ProofType": "N/A",
                                "Rating": {
                                    "Weiss": {
                                        "Rating": "C+",
                                        "TechnologyAdoptionRating": "B-",
                                        "MarketPerformanceRating": "D+"
                                    }
                                },
                                "NetHashesPerSecond": 0,
                                "BlockNumber": 62183770,
                                "BlockTime": 0,
                                "BlockReward": 0,
                                "AssetLaunchDate": "2013-01-01",
                                "MaxSupply": 100000000000,
                                "Type": 1,
                                "DocumentType": "Webpagecoinp"
                            },
                            "RAW": {
                                "USD": {
                                    "TYPE": "5",
                                    "MARKET": "CCCAGG",
                                    "FROMSYMBOL": "XRP",
                                    "TOSYMBOL": "USD",
                                    "FLAGS": "2052",
                                    "PRICE": 0.459,
                                    "LASTUPDATE": 1615662647,
                                    "MEDIAN": 0.4589,
                                    "LASTVOLUME": 50,
                                    "LASTVOLUMETO": 22.961,
                                    "LASTTRADEID": "641934349",
                                    "VOLUMEDAY": 89926893.6993341,
                                    "VOLUMEDAYTO": 40273367.53470199,
                                    "VOLUME24HOUR": 102782375.49673654,
                                    "VOLUME24HOURTO": 45897202.57244383,
                                    "OPENDAY": 0.4397,
                                    "HIGHDAY": 0.4664,
                                    "LOWDAY": 0.4326,
                                    "OPEN24HOUR": 0.4382,
                                    "HIGH24HOUR": 0.4666,
                                    "LOW24HOUR": 0.4324,
                                    "LASTMARKET": "Bitfinex",
                                    "VOLUMEHOUR": 216348.35490560991,
                                    "VOLUMEHOURTO": 99366.32271902503,
                                    "OPENHOUR": 0.4601,
                                    "HIGHHOUR": 0.4601,
                                    "LOWHOUR": 0.4587,
                                    "TOPTIERVOLUME24HOUR": 102782375.49673654,
                                    "TOPTIERVOLUME24HOURTO": 45897202.57244383,
                                    "CHANGE24HOUR": 0.02080000000000004,
                                    "CHANGEPCT24HOUR": 4.746691008671848,
                                    "CHANGEDAY": 0.01930000000000004,
                                    "CHANGEPCTDAY": 4.389356379349565,
                                    "CHANGEHOUR": -0.0010999999999999899,
                                    "CHANGEPCTHOUR": -0.23907846120408385,
                                    "CONVERSIONTYPE": "direct",
                                    "CONVERSIONSYMBOL": "",
                                    "SUPPLY": 99990664689,
                                    "MKTCAP": 45895715092.251,
                                    "MKTCAPPENALTY": 0,
                                    "TOTALVOLUME24H": 2232713517.1028886,
                                    "TOTALVOLUME24HTO": 1023535596.5696677,
                                    "TOTALTOPTIERVOLUME24H": 2229527485.0793014,
                                    "TOTALTOPTIERVOLUME24HTO": 1022073207.8708411,
                                    "IMAGEURL": "/media/37746347/xrp.png"
                                }
                            },
                            "DISPLAY": {
                                "USD": {
                                    "FROMSYMBOL": "XRP",
                                    "TOSYMBOL": "$",
                                    "MARKET": "CryptoCompare Index",
                                    "PRICE": "$ 0.4590",
                                    "LASTUPDATE": "Just now",
                                    "LASTVOLUME": "XRP 50.00",
                                    "LASTVOLUMETO": "$ 22.96",
                                    "LASTTRADEID": "641934349",
                                    "VOLUMEDAY": "XRP 89,926,893.7",
                                    "VOLUMEDAYTO": "$ 40,273,367.5",
                                    "VOLUME24HOUR": "XRP 102,782,375.5",
                                    "VOLUME24HOURTO": "$ 45,897,202.6",
                                    "OPENDAY": "$ 0.4397",
                                    "HIGHDAY": "$ 0.4664",
                                    "LOWDAY": "$ 0.4326",
                                    "OPEN24HOUR": "$ 0.4382",
                                    "HIGH24HOUR": "$ 0.4666",
                                    "LOW24HOUR": "$ 0.4324",
                                    "LASTMARKET": "Bitfinex",
                                    "VOLUMEHOUR": "XRP 216,348.4",
                                    "VOLUMEHOURTO": "$ 99,366.3",
                                    "OPENHOUR": "$ 0.4601",
                                    "HIGHHOUR": "$ 0.4601",
                                    "LOWHOUR": "$ 0.4587",
                                    "TOPTIERVOLUME24HOUR": "XRP 102,782,375.5",
                                    "TOPTIERVOLUME24HOURTO": "$ 45,897,202.6",
                                    "CHANGE24HOUR": "$ 0.021",
                                    "CHANGEPCT24HOUR": "4.75",
                                    "CHANGEDAY": "$ 0.019",
                                    "CHANGEPCTDAY": "4.39",
                                    "CHANGEHOUR": "$ -0.0011",
                                    "CHANGEPCTHOUR": "-0.24",
                                    "CONVERSIONTYPE": "direct",
                                    "CONVERSIONSYMBOL": "",
                                    "SUPPLY": "XRP 99,990,664,689.0",
                                    "MKTCAP": "$ 45.90 B",
                                    "MKTCAPPENALTY": "0 %",
                                    "TOTALVOLUME24H": "XRP 2.23 B",
                                    "TOTALVOLUME24HTO": "$ 1.02 B",
                                    "TOTALTOPTIERVOLUME24H": "XRP 2.23 B",
                                    "TOTALTOPTIERVOLUME24HTO": "$ 1.02 B",
                                    "IMAGEURL": "/media/37746347/xrp.png"
                                }
                            }
                        },
                        {
                            "CoinInfo": {
                                "Id": "202330",
                                "Name": "BCH",
                                "FullName": "Bitcoin Cash",
                                "Internal": "BCH",
                                "ImageUrl": "/media/37746245/bch.png",
                                "Url": "/coins/bch/overview",
                                "Algorithm": "SHA-256",
                                "ProofType": "PoW",
                                "Rating": {
                                    "Weiss": {
                                        "Rating": "C+",
                                        "TechnologyAdoptionRating": "B-",
                                        "MarketPerformanceRating": "D-"
                                    }
                                },
                                "NetHashesPerSecond": 1388834588299910700,
                                "BlockNumber": 678591,
                                "BlockTime": 580,
                                "BlockReward": 6.25360588,
                                "AssetLaunchDate": "2017-08-01",
                                "MaxSupply": 20999999.9769,
                                "Type": 1,
                                "DocumentType": "Webpagecoinp"
                            },
                            "RAW": {
                                "USD": {
                                    "TYPE": "5",
                                    "MARKET": "CCCAGG",
                                    "FROMSYMBOL": "BCH",
                                    "TOSYMBOL": "USD",
                                    "FLAGS": "2052",
                                    "PRICE": 598.2,
                                    "LASTUPDATE": 1615662647,
                                    "MEDIAN": 598.1,
                                    "LASTVOLUME": 0.16715239,
                                    "LASTVOLUMETO": 100.023990176,
                                    "LASTTRADEID": "5WQDTDZEYM3M",
                                    "VOLUMEDAY": 113843.51830803957,
                                    "VOLUMEDAYTO": 64587062.32329207,
                                    "VOLUME24HOUR": 125287.68853620999,
                                    "VOLUME24HOURTO": 70676580.10331261,
                                    "OPENDAY": 538.51,
                                    "HIGHDAY": 599.27,
                                    "LOWDAY": 522.53,
                                    "OPEN24HOUR": 526.31,
                                    "HIGH24HOUR": 599.33,
                                    "LOW24HOUR": 522.01,
                                    "LASTMARKET": "itBit",
                                    "VOLUMEHOUR": 644.6927448699995,
                                    "VOLUMEHOURTO": 385061.8347043997,
                                    "OPENHOUR": 597.75,
                                    "HIGHHOUR": 598.29,
                                    "LOWHOUR": 596.07,
                                    "TOPTIERVOLUME24HOUR": 125287.68853620999,
                                    "TOPTIERVOLUME24HOURTO": 70676580.10331261,
                                    "CHANGE24HOUR": 71.8900000000001,
                                    "CHANGEPCT24HOUR": 13.65925025175279,
                                    "CHANGEDAY": 59.690000000000055,
                                    "CHANGEPCTDAY": 11.084288128354173,
                                    "CHANGEHOUR": 0.4500000000000455,
                                    "CHANGEPCTHOUR": 0.0752823086574731,
                                    "CONVERSIONTYPE": "direct",
                                    "CONVERSIONSYMBOL": "",
                                    "SUPPLY": 18678681.14678956,
                                    "MKTCAP": 11173587062.009514,
                                    "MKTCAPPENALTY": 0,
                                    "TOTALVOLUME24H": 1653794.1512729174,
                                    "TOTALVOLUME24HTO": 985029146.112411,
                                    "TOTALTOPTIERVOLUME24H": 1652761.861852552,
                                    "TOTALTOPTIERVOLUME24HTO": 984411630.5811485,
                                    "IMAGEURL": "/media/37746245/bch.png"
                                }
                            },
                            "DISPLAY": {
                                "USD": {
                                    "FROMSYMBOL": "BCH",
                                    "TOSYMBOL": "$",
                                    "MARKET": "CryptoCompare Index",
                                    "PRICE": "$ 598.20",
                                    "LASTUPDATE": "Just now",
                                    "LASTVOLUME": "BCH 0.1672",
                                    "LASTVOLUMETO": "$ 100.02",
                                    "LASTTRADEID": "5WQDTDZEYM3M",
                                    "VOLUMEDAY": "BCH 113,843.5",
                                    "VOLUMEDAYTO": "$ 64,587,062.3",
                                    "VOLUME24HOUR": "BCH 125,287.7",
                                    "VOLUME24HOURTO": "$ 70,676,580.1",
                                    "OPENDAY": "$ 538.51",
                                    "HIGHDAY": "$ 599.27",
                                    "LOWDAY": "$ 522.53",
                                    "OPEN24HOUR": "$ 526.31",
                                    "HIGH24HOUR": "$ 599.33",
                                    "LOW24HOUR": "$ 522.01",
                                    "LASTMARKET": "itBit",
                                    "VOLUMEHOUR": "BCH 644.69",
                                    "VOLUMEHOURTO": "$ 385,061.8",
                                    "OPENHOUR": "$ 597.75",
                                    "HIGHHOUR": "$ 598.29",
                                    "LOWHOUR": "$ 596.07",
                                    "TOPTIERVOLUME24HOUR": "BCH 125,287.7",
                                    "TOPTIERVOLUME24HOURTO": "$ 70,676,580.1",
                                    "CHANGE24HOUR": "$ 71.89",
                                    "CHANGEPCT24HOUR": "13.66",
                                    "CHANGEDAY": "$ 59.69",
                                    "CHANGEPCTDAY": "11.08",
                                    "CHANGEHOUR": "$ 0.45",
                                    "CHANGEPCTHOUR": "0.08",
                                    "CONVERSIONTYPE": "direct",
                                    "CONVERSIONSYMBOL": "",
                                    "SUPPLY": "BCH 18,678,681.1",
                                    "MKTCAP": "$ 11.17 B",
                                    "MKTCAPPENALTY": "0 %",
                                    "TOTALVOLUME24H": "BCH 1.65 M",
                                    "TOTALVOLUME24HTO": "$ 985.03 M",
                                    "TOTALTOPTIERVOLUME24H": "BCH 1.65 M",
                                    "TOTALTOPTIERVOLUME24HTO": "$ 984.41 M",
                                    "IMAGEURL": "/media/37746245/bch.png"
                                }
                            }
                        },
                        {
                            "CoinInfo": {
                                "Id": "930686",
                                "Name": "CHR",
                                "FullName": "Chromia",
                                "Internal": "CHR",
                                "ImageUrl": "/media/35650736/chr.png",
                                "Url": "/coins/chr/overview",
                                "Algorithm": "N/A",
                                "ProofType": "N/A",
                                "Rating": {
                                    "Weiss": {
                                        "Rating": "",
                                        "TechnologyAdoptionRating": "",
                                        "MarketPerformanceRating": ""
                                    }
                                },
                                "NetHashesPerSecond": 0,
                                "BlockNumber": 0,
                                "BlockTime": 0,
                                "BlockReward": 0,
                                "AssetLaunchDate": "2019-05-27",
                                "MaxSupply": -1,
                                "Type": 1,
                                "DocumentType": "Webpagecoinp"
                            },
                            "RAW": {
                                "USD": {
                                    "TYPE": "5",
                                    "MARKET": "CCCAGG",
                                    "FROMSYMBOL": "CHR",
                                    "TOSYMBOL": "USD",
                                    "FLAGS": "2052",
                                    "PRICE": 0.5770886087999999,
                                    "LASTUPDATE": 1615662657,
                                    "MEDIAN": 0.5816817350000001,
                                    "LASTVOLUME": 5.8246,
                                    "LASTVOLUMETO": 3.36131031081648,
                                    "LASTTRADEID": "1612701886755",
                                    "VOLUMEDAY": 179607674.3281429,
                                    "VOLUMEDAYTO": 103649542.9078314,
                                    "VOLUME24HOUR": 249927910.2513641,
                                    "VOLUME24HOURTO": 144230550.0272509,
                                    "OPENDAY": 0.5679779328,
                                    "HIGHDAY": 0.8091096299000001,
                                    "LOWDAY": 0.5178336436,
                                    "OPEN24HOUR": 0.501891604,
                                    "HIGH24HOUR": 0.8125244736,
                                    "LOW24HOUR": 0.4812799134,
                                    "LASTMARKET": "Kucoin",
                                    "VOLUMEHOUR": 810302.2211759418,
                                    "VOLUMEHOURTO": 467616.1815259741,
                                    "OPENHOUR": 0.584859366,
                                    "HIGHHOUR": 0.591113068,
                                    "LOWHOUR": 0.5762756373,
                                    "TOPTIERVOLUME24HOUR": 249927910.2513641,
                                    "TOPTIERVOLUME24HOURTO": 144230550.0272509,
                                    "CHANGE24HOUR": 0.07519700479999991,
                                    "CHANGEPCT24HOUR": 14.982718220566191,
                                    "CHANGEDAY": 0.009110675999999929,
                                    "CHANGEPCTDAY": 1.6040545721708588,
                                    "CHANGEHOUR": -0.007770757200000089,
                                    "CHANGEPCTHOUR": -1.3286539725175726,
                                    "CONVERSIONTYPE": "multiply",
                                    "CONVERSIONSYMBOL": "BTC",
                                    "SUPPLY": 552247804.326204,
                                    "MKTCAP": 318695917.1114636,
                                    "MKTCAPPENALTY": 0,
                                    "TOTALVOLUME24H": 1637418060.5905797,
                                    "TOTALVOLUME24HTO": 944935310.6102116,
                                    "TOTALTOPTIERVOLUME24H": 1637418060.5905797,
                                    "TOTALTOPTIERVOLUME24HTO": 944935310.6102116,
                                    "IMAGEURL": "/media/35650736/chr.png"
                                }
                            },
                            "DISPLAY": {
                                "USD": {
                                    "FROMSYMBOL": "CHR",
                                    "TOSYMBOL": "$",
                                    "MARKET": "CryptoCompare Index",
                                    "PRICE": "$ 0.5771",
                                    "LASTUPDATE": "Just now",
                                    "LASTVOLUME": "CHR 5.82",
                                    "LASTVOLUMETO": "$ 3.36",
                                    "LASTTRADEID": "1612701886755",
                                    "VOLUMEDAY": "CHR 179,607,674.3",
                                    "VOLUMEDAYTO": "$ 103,649,542.9",
                                    "VOLUME24HOUR": "CHR 249,927,910.3",
                                    "VOLUME24HOURTO": "$ 144,230,550.0",
                                    "OPENDAY": "$ 0.5680",
                                    "HIGHDAY": "$ 0.8091",
                                    "LOWDAY": "$ 0.5178",
                                    "OPEN24HOUR": "$ 0.5019",
                                    "HIGH24HOUR": "$ 0.8125",
                                    "LOW24HOUR": "$ 0.4813",
                                    "LASTMARKET": "Kucoin",
                                    "VOLUMEHOUR": "CHR 810,302.2",
                                    "VOLUMEHOURTO": "$ 467,616.2",
                                    "OPENHOUR": "$ 0.5849",
                                    "HIGHHOUR": "$ 0.5911",
                                    "LOWHOUR": "$ 0.5763",
                                    "TOPTIERVOLUME24HOUR": "CHR 249,927,910.3",
                                    "TOPTIERVOLUME24HOURTO": "$ 144,230,550.0",
                                    "CHANGE24HOUR": "$ 0.075",
                                    "CHANGEPCT24HOUR": "14.98",
                                    "CHANGEDAY": "$ 0.0091",
                                    "CHANGEPCTDAY": "1.60",
                                    "CHANGEHOUR": "$ -0.0078",
                                    "CHANGEPCTHOUR": "-1.33",
                                    "CONVERSIONTYPE": "multiply",
                                    "CONVERSIONSYMBOL": "BTC",
                                    "SUPPLY": "CHR 552,247,804.3",
                                    "MKTCAP": "$ 318.70 M",
                                    "MKTCAPPENALTY": "0 %",
                                    "TOTALVOLUME24H": "CHR 1.64 B",
                                    "TOTALVOLUME24HTO": "$ 944.94 M",
                                    "TOTALTOPTIERVOLUME24H": "CHR 1.64 B",
                                    "TOTALTOPTIERVOLUME24HTO": "$ 944.94 M",
                                    "IMAGEURL": "/media/35650736/chr.png"
                                }
                            }
                        }
                    ].map(items => ))
                }, 1000)
            }, [])

            return (
                <TableContainer component={Paper}>
                    <Table className={classes.table} size="small" aria-label="a dense table">
                        <TableHead>
                            <TableRow>
                                <TableCell></TableCell>
                                <TableCell align="left">Name</TableCell>
                                <TableCell align="left">FullName</TableCell>
                                <TableCell align="left">Price</TableCell>
                                <TableCell align="left">volume24hour</TableCell>
                            </TableRow>
                        </TableHead>
                        <TableBody>
                            {!items.length ? '...Loading' : items.map((coin) => (
                                <TableRow key={coin.name}>
                                    <TableCell><img className={classes.currencyIcon} src={coin.imageUrl}
                                                    alt={coin.name}/></TableCell>
                                    <TableCell align="left">{coin.name}</TableCell>
                                    <TableCell align="left">{coin.fullName}</TableCell>
                                    <TableCell className={diffObj[coin.name]} align="left">${coin.price}</TableCell>
                                    <TableCell align="left">${coin.volume24Hour}</TableCell>
                                </TableRow>
                            ))}
                        </TableBody>
                    </Table>
                </TableContainer>
            )
        }
    )
);


export default CryptoTable;
